/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AuroraMosaic {
  export type PanelMetaStruct = {
    width: BigNumberish;
    height: BigNumberish;
    isSealed: boolean;
    createdAt: BigNumberish;
    sealedAt: BigNumberish;
    encryptedBrushCount: BytesLike;
    lastLoreCID: string;
  };

  export type PanelMetaStructOutput = [
    width: bigint,
    height: bigint,
    isSealed: boolean,
    createdAt: bigint,
    sealedAt: bigint,
    encryptedBrushCount: string,
    lastLoreCID: string
  ] & {
    width: bigint;
    height: bigint;
    isSealed: boolean;
    createdAt: bigint;
    sealedAt: bigint;
    encryptedBrushCount: string;
    lastLoreCID: string;
  };

  export type TileViewStruct = {
    encryptedColor: BytesLike;
    artisan: AddressLike;
    updatedAt: BigNumberish;
  };

  export type TileViewStructOutput = [
    encryptedColor: string,
    artisan: string,
    updatedAt: bigint
  ] & { encryptedColor: string; artisan: string; updatedAt: bigint };
}

export interface AuroraMosaicInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BRUSH_COOLDOWN"
      | "MAX_DIMENSION"
      | "applyTile"
      | "approve"
      | "artisanContribution"
      | "balanceOf"
      | "describePanel"
      | "forgePanelRelic"
      | "getApproved"
      | "initiatePanel"
      | "isApprovedForAll"
      | "lastBrushAt"
      | "name"
      | "ownerOf"
      | "panelBrushTotal"
      | "panelRelicId"
      | "protocolId"
      | "safeTransferFrom(address,address,uint256)"
      | "safeTransferFrom(address,address,uint256,bytes)"
      | "sealPanel"
      | "setApprovalForAll"
      | "supportsInterface"
      | "symbol"
      | "tileColor"
      | "tokenURI"
      | "transferFrom"
      | "viewTile"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "ApprovalForAll"
      | "BatchMetadataUpdate"
      | "MetadataUpdate"
      | "PanelForged"
      | "PanelSealed"
      | "PanelStarted"
      | "TileBrushed"
      | "Transfer"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BRUSH_COOLDOWN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_DIMENSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "applyTile",
    values: [BigNumberish, BigNumberish, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "artisanContribution",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "describePanel",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "forgePanelRelic",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initiatePanel",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastBrushAt",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "panelBrushTotal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "panelRelicId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sealPanel",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tileColor",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "viewTile",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "BRUSH_COOLDOWN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_DIMENSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "applyTile", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "artisanContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "describePanel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forgePanelRelic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initiatePanel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastBrushAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "panelBrushTotal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "panelRelicId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sealPanel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tileColor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "viewTile", data: BytesLike): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    approved: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
  export interface OutputObject {
    owner: string;
    approved: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalForAllEvent {
  export type InputTuple = [
    owner: AddressLike,
    operator: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    owner: string,
    operator: string,
    approved: boolean
  ];
  export interface OutputObject {
    owner: string;
    operator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BatchMetadataUpdateEvent {
  export type InputTuple = [
    _fromTokenId: BigNumberish,
    _toTokenId: BigNumberish
  ];
  export type OutputTuple = [_fromTokenId: bigint, _toTokenId: bigint];
  export interface OutputObject {
    _fromTokenId: bigint;
    _toTokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MetadataUpdateEvent {
  export type InputTuple = [_tokenId: BigNumberish];
  export type OutputTuple = [_tokenId: bigint];
  export interface OutputObject {
    _tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PanelForgedEvent {
  export type InputTuple = [
    panelId: BigNumberish,
    relicId: BigNumberish,
    minter: AddressLike,
    loreCID: string
  ];
  export type OutputTuple = [
    panelId: bigint,
    relicId: bigint,
    minter: string,
    loreCID: string
  ];
  export interface OutputObject {
    panelId: bigint;
    relicId: bigint;
    minter: string;
    loreCID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PanelSealedEvent {
  export type InputTuple = [panelId: BigNumberish, sealingArtist: AddressLike];
  export type OutputTuple = [panelId: bigint, sealingArtist: string];
  export interface OutputObject {
    panelId: bigint;
    sealingArtist: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PanelStartedEvent {
  export type InputTuple = [
    panelId: BigNumberish,
    width: BigNumberish,
    height: BigNumberish,
    curator: AddressLike
  ];
  export type OutputTuple = [
    panelId: bigint,
    width: bigint,
    height: bigint,
    curator: string
  ];
  export interface OutputObject {
    panelId: bigint;
    width: bigint;
    height: bigint;
    curator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TileBrushedEvent {
  export type InputTuple = [
    panelId: BigNumberish,
    x: BigNumberish,
    y: BigNumberish,
    artisan: AddressLike,
    encryptedColorHandle: BytesLike
  ];
  export type OutputTuple = [
    panelId: bigint,
    x: bigint,
    y: bigint,
    artisan: string,
    encryptedColorHandle: string
  ];
  export interface OutputObject {
    panelId: bigint;
    x: bigint;
    y: bigint;
    artisan: string;
    encryptedColorHandle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, tokenId: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AuroraMosaic extends BaseContract {
  connect(runner?: ContractRunner | null): AuroraMosaic;
  waitForDeployment(): Promise<this>;

  interface: AuroraMosaicInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BRUSH_COOLDOWN: TypedContractMethod<[], [bigint], "view">;

  MAX_DIMENSION: TypedContractMethod<[], [bigint], "view">;

  applyTile: TypedContractMethod<
    [
      panelId: BigNumberish,
      x: BigNumberish,
      y: BigNumberish,
      encryptedColorExt: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  approve: TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  artisanContribution: TypedContractMethod<
    [artisan: AddressLike],
    [string],
    "view"
  >;

  balanceOf: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  describePanel: TypedContractMethod<
    [panelId: BigNumberish],
    [
      [AuroraMosaic.PanelMetaStructOutput, bigint] & {
        meta: AuroraMosaic.PanelMetaStructOutput;
        relicId: bigint;
      }
    ],
    "view"
  >;

  forgePanelRelic: TypedContractMethod<
    [panelId: BigNumberish, loreCID: string],
    [bigint],
    "nonpayable"
  >;

  getApproved: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  initiatePanel: TypedContractMethod<
    [width: BigNumberish, height: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  isApprovedForAll: TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;

  lastBrushAt: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  name: TypedContractMethod<[], [string], "view">;

  ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  panelBrushTotal: TypedContractMethod<
    [panelId: BigNumberish],
    [string],
    "view"
  >;

  panelRelicId: TypedContractMethod<[panelId: BigNumberish], [bigint], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  "safeTransferFrom(address,address,uint256)": TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  sealPanel: TypedContractMethod<[panelId: BigNumberish], [void], "nonpayable">;

  setApprovalForAll: TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  tileColor: TypedContractMethod<
    [panelId: BigNumberish, x: BigNumberish, y: BigNumberish],
    [string],
    "view"
  >;

  tokenURI: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  viewTile: TypedContractMethod<
    [panelId: BigNumberish, x: BigNumberish, y: BigNumberish],
    [AuroraMosaic.TileViewStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BRUSH_COOLDOWN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_DIMENSION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "applyTile"
  ): TypedContractMethod<
    [
      panelId: BigNumberish,
      x: BigNumberish,
      y: BigNumberish,
      encryptedColorExt: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "artisanContribution"
  ): TypedContractMethod<[artisan: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "describePanel"
  ): TypedContractMethod<
    [panelId: BigNumberish],
    [
      [AuroraMosaic.PanelMetaStructOutput, bigint] & {
        meta: AuroraMosaic.PanelMetaStructOutput;
        relicId: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "forgePanelRelic"
  ): TypedContractMethod<
    [panelId: BigNumberish, loreCID: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getApproved"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "initiatePanel"
  ): TypedContractMethod<
    [width: BigNumberish, height: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isApprovedForAll"
  ): TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "lastBrushAt"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "panelBrushTotal"
  ): TypedContractMethod<[panelId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "panelRelicId"
  ): TypedContractMethod<[panelId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256)"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256,bytes)"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sealPanel"
  ): TypedContractMethod<[panelId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setApprovalForAll"
  ): TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tileColor"
  ): TypedContractMethod<
    [panelId: BigNumberish, x: BigNumberish, y: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "tokenURI"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "viewTile"
  ): TypedContractMethod<
    [panelId: BigNumberish, x: BigNumberish, y: BigNumberish],
    [AuroraMosaic.TileViewStructOutput],
    "view"
  >;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "ApprovalForAll"
  ): TypedContractEvent<
    ApprovalForAllEvent.InputTuple,
    ApprovalForAllEvent.OutputTuple,
    ApprovalForAllEvent.OutputObject
  >;
  getEvent(
    key: "BatchMetadataUpdate"
  ): TypedContractEvent<
    BatchMetadataUpdateEvent.InputTuple,
    BatchMetadataUpdateEvent.OutputTuple,
    BatchMetadataUpdateEvent.OutputObject
  >;
  getEvent(
    key: "MetadataUpdate"
  ): TypedContractEvent<
    MetadataUpdateEvent.InputTuple,
    MetadataUpdateEvent.OutputTuple,
    MetadataUpdateEvent.OutputObject
  >;
  getEvent(
    key: "PanelForged"
  ): TypedContractEvent<
    PanelForgedEvent.InputTuple,
    PanelForgedEvent.OutputTuple,
    PanelForgedEvent.OutputObject
  >;
  getEvent(
    key: "PanelSealed"
  ): TypedContractEvent<
    PanelSealedEvent.InputTuple,
    PanelSealedEvent.OutputTuple,
    PanelSealedEvent.OutputObject
  >;
  getEvent(
    key: "PanelStarted"
  ): TypedContractEvent<
    PanelStartedEvent.InputTuple,
    PanelStartedEvent.OutputTuple,
    PanelStartedEvent.OutputObject
  >;
  getEvent(
    key: "TileBrushed"
  ): TypedContractEvent<
    TileBrushedEvent.InputTuple,
    TileBrushedEvent.OutputTuple,
    TileBrushedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "ApprovalForAll(address,address,bool)": TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;
    ApprovalForAll: TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;

    "BatchMetadataUpdate(uint256,uint256)": TypedContractEvent<
      BatchMetadataUpdateEvent.InputTuple,
      BatchMetadataUpdateEvent.OutputTuple,
      BatchMetadataUpdateEvent.OutputObject
    >;
    BatchMetadataUpdate: TypedContractEvent<
      BatchMetadataUpdateEvent.InputTuple,
      BatchMetadataUpdateEvent.OutputTuple,
      BatchMetadataUpdateEvent.OutputObject
    >;

    "MetadataUpdate(uint256)": TypedContractEvent<
      MetadataUpdateEvent.InputTuple,
      MetadataUpdateEvent.OutputTuple,
      MetadataUpdateEvent.OutputObject
    >;
    MetadataUpdate: TypedContractEvent<
      MetadataUpdateEvent.InputTuple,
      MetadataUpdateEvent.OutputTuple,
      MetadataUpdateEvent.OutputObject
    >;

    "PanelForged(uint256,uint256,address,string)": TypedContractEvent<
      PanelForgedEvent.InputTuple,
      PanelForgedEvent.OutputTuple,
      PanelForgedEvent.OutputObject
    >;
    PanelForged: TypedContractEvent<
      PanelForgedEvent.InputTuple,
      PanelForgedEvent.OutputTuple,
      PanelForgedEvent.OutputObject
    >;

    "PanelSealed(uint256,address)": TypedContractEvent<
      PanelSealedEvent.InputTuple,
      PanelSealedEvent.OutputTuple,
      PanelSealedEvent.OutputObject
    >;
    PanelSealed: TypedContractEvent<
      PanelSealedEvent.InputTuple,
      PanelSealedEvent.OutputTuple,
      PanelSealedEvent.OutputObject
    >;

    "PanelStarted(uint256,uint16,uint16,address)": TypedContractEvent<
      PanelStartedEvent.InputTuple,
      PanelStartedEvent.OutputTuple,
      PanelStartedEvent.OutputObject
    >;
    PanelStarted: TypedContractEvent<
      PanelStartedEvent.InputTuple,
      PanelStartedEvent.OutputTuple,
      PanelStartedEvent.OutputObject
    >;

    "TileBrushed(uint256,uint256,uint256,address,bytes32)": TypedContractEvent<
      TileBrushedEvent.InputTuple,
      TileBrushedEvent.OutputTuple,
      TileBrushedEvent.OutputObject
    >;
    TileBrushed: TypedContractEvent<
      TileBrushedEvent.InputTuple,
      TileBrushedEvent.OutputTuple,
      TileBrushedEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
  };
}
